---
version: "3"

services:
  database:
    container_name: mijnpe-database
    image: "postgres:latest"
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file:
      - .env
  mailcatcher:
    container_name: mijnpe-mailcatcher
    image: schickling/mailcatcher
    restart: unless-stopped
    ports:
      - 8081:1080
      - 1025:1025
    env_file:
      - .env
  adminer:
    container_name: mijnpe-adminer
    image: adminer
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: database
    env_file:
      - .env
  redis:
    image: docker.io/library/redis:alpine
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
  authentik:
    image: ghcr.io/proteus-eretes/authentik:1669585997-ca3bbee
    restart: unless-stopped
    command: server
    environment:
      AUTHENTIK_BOOTSTRAP_TOKEN: ${AUTHENTIK_TOKEN}
      AUTHENTIK_SECRET_KEY: "!!!SECRET!!!"
      AUTHENTIK_AVATARS: none
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_REDIS__DB: 1
      AUTHENTIK_POSTGRESQL__HOST: database
      AUTHENTIK_POSTGRESQL__USER: ${POSTGRES_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${POSTGRES_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${POSTGRES_PASSWORD}
      AUTHENTIK_ERROR_REPORTING__ENABLED: "false"
      AUTHENTIK_BOOTSTRAP_PASSWORD: "temppassword"
      AUTHENTIK_EMAIL__HOST: mailcatcher
      AUTHENTIK_EMAIL__PORT: 1025
      AUTHENTIK_EMAIL__USE_TLS: false
      AUTHENTIK_EMAIL__USE_SSL: false
      AUTHENTIK_EMAIL__TIMEOUT: 10
      AUTHENTIK_EMAIL__FROM: authentik@localhost
    ports:
      - "9000:9000"
  worker:
    image: ghcr.io/proteus-eretes/authentik:1669585997-ca3bbee
    restart: unless-stopped
    command: worker
    environment:
      AUTHENTIK_BOOTSTRAP_TOKEN: ${AUTHENTIK_TOKEN}
      AUTHENTIK_SECRET_KEY: "!!!SECRET!!!"
      AUTHENTIK_AVATARS: none
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_REDIS__DB: 1
      AUTHENTIK_POSTGRESQL__HOST: database
      AUTHENTIK_POSTGRESQL__USER: ${POSTGRES_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${POSTGRES_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${POSTGRES_PASSWORD}
      AUTHENTIK_ERROR_REPORTING__ENABLED: "false"
      AUTHENTIK_BOOTSTRAP_PASSWORD: "temppassword"
      AUTHENTIK_EMAIL__HOST: mailcatcher
      AUTHENTIK_EMAIL__PORT: 1025
      AUTHENTIK_EMAIL__USE_TLS: false
      AUTHENTIK_EMAIL__USE_SSL: false
      AUTHENTIK_EMAIL__TIMEOUT: 10
      AUTHENTIK_EMAIL__FROM: authentik@localhost
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
