---
version: "3"

services:
  database:
    container_name: mijnpe-database
    image: "postgres:latest"
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file:
      - .env
  mailcatcher:
    container_name: mijnpe-mailcatcher
    image: schickling/mailcatcher
    restart: unless-stopped
    ports:
      - 8081:1080
      - 1025:1025
    env_file:
      - .env
  adminer:
    container_name: mijnpe-adminer
    image: adminer
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: database
    env_file:
      - .env
