---
contact_links:
  - name: 📚 Documentatie
    url: https://github.com/Proteus-Eretes/mijn-proteus/wiki
    about: Lees de wiki voor uitgebreide documentatie
  - name: 💬 Discussions
    url: https://github.com/Proteus-Eretes/mijn-proteus/discussions
    about: Gebruik discussions voor vragen en ideeën
