version: 1
metadata:
  name: Proteus Develop - Mijn PE Application
entries:
  - model: authentik_blueprints.metaapplyblueprint
    attrs:
      identifiers:
        name: Proteus Develop - Mijn PE Provider
      required: true
  - model: authentik_core.application
    identifiers:
      name: Mijn Proteus
    attrs:
      name: Mijn Proteus
      slug: mijnpe
      open_in_new_tab: true
      policy_engine_mode: any
      provider:
        !Find [authentik_providers_oauth2.oauth2provider, [name, Mijn Proteus]]
      meta_description: Voor al uw verenigingsbenodigdheden
      meta_launch_url: http://localhost:3000/
      meta_publisher: D.S.R. Proteus-Eretes
